# Generated by Django 5.2.4 on 2025-08-15 18:53

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre completo')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo electrónico')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('tipo_documento', models.CharField(choices=[('dni', 'DNI'), ('ruc', 'RUC'), ('ce', 'Carné de Extranjería'), ('pasaporte', 'Pasaporte')], default='dni', max_length=10, verbose_name='Tipo de documento')),
                ('numero_documento', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número de documento')),
                ('direccion', models.TextField(blank=True, null=True, verbose_name='Dirección')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('activo', models.BooleanField(default=True, verbose_name='Cliente activo')),
                ('usuario', models.ForeignKey(help_text='Usuario que posee este cliente', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario propietario')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_venta', models.CharField(max_length=20, verbose_name='Número de venta')),
                ('fecha_venta', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de venta')),
                ('cliente_nombre', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre del cliente (venta anónima)')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Subtotal')),
                ('porcentaje_descuento', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Porcentaje de descuento aplicado a la venta (0-100)', max_digits=5, verbose_name='Porcentaje de descuento')),
                ('descuento', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Descuento')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Total')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('completada', 'Completada'), ('cancelada', 'Cancelada'), ('reembolsada', 'Reembolsada')], default='pendiente', max_length=12, verbose_name='Estado')),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta de crédito/débito'), ('transferencia', 'Transferencia bancaria'), ('yape', 'Yape'), ('plin', 'Plin'), ('otro', 'Otro')], default='efectivo', max_length=15, verbose_name='Método de pago')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('vendedor', models.CharField(blank=True, max_length=100, null=True, verbose_name='Vendedor')),
                ('external_reference', models.CharField(blank=True, max_length=100, null=True, verbose_name='Referencia externa de pago')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas', to='ventas.cliente', verbose_name='Cliente')),
                ('usuario', models.ForeignKey(help_text='Usuario que posee esta venta', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario propietario')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'ordering': ['-fecha_venta'],
            },
        ),
        migrations.CreateModel(
            name='ItemVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad')),
                ('descuento_item', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Descuento del item')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Subtotal del item')),
                ('color', models.ForeignKey(blank=True, help_text='Color específico del producto vendido', null=True, on_delete=django.db.models.deletion.SET_NULL, to='productos.colorproducto', verbose_name='Color específico')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto', verbose_name='Producto')),
                ('variante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='productos.varianteproducto', verbose_name='Variante')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ventas.venta', verbose_name='Venta')),
            ],
            options={
                'verbose_name': 'Item de venta',
                'verbose_name_plural': 'Items de venta',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['usuario', 'nombre'], name='ventas_clie_usuario_f59318_idx'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['usuario', 'email'], name='ventas_clie_usuario_a776c2_idx'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['usuario', 'numero_documento'], name='ventas_clie_usuario_a9910a_idx'),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['usuario', 'numero_venta'], name='ventas_vent_usuario_943270_idx'),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['usuario', 'fecha_venta'], name='ventas_vent_usuario_026a00_idx'),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['usuario', 'estado'], name='ventas_vent_usuario_8c1ca9_idx'),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['usuario', 'cliente'], name='ventas_vent_usuario_a88013_idx'),
        ),
    ]
