# Generated by Django 5.2.4 on 2025-08-15 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='numero_venta',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Número de venta'),
        ),
    ]
