# Generated by Django 5.2.4 on 2025-07-19 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_colorproducto_stock_and_more'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemventa',
            name='color',
            field=models.ForeignKey(blank=True, help_text='Color específico del producto vendido', null=True, on_delete=django.db.models.deletion.SET_NULL, to='productos.colorproducto', verbose_name='Color específico'),
        ),
    ]
