# Generated by Django 5.2.4 on 2025-07-21 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_add_color_to_itemventa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='metodo_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta de crédito/débito'), ('transferencia', 'Transferencia bancaria'), ('yape', 'Yape'), ('plin', 'Plin'), ('otro', 'Otro')], default='efectivo', max_length=15, verbose_name='Método de pago'),
        ),
    ]
