# Generated by Django manually to fix usuario_id column issue

from django.db import migrations, models
from django.db import connection


def fix_usuario_id_column(apps, schema_editor):
    """
    Función para manejar el campo usuario_id problemático
    """
    with connection.cursor() as cursor:
        # Verificar si la columna usuario_id existe
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name = 'ventas_cliente' AND column_name = 'usuario_id';
        """)
        
        if cursor.fetchone():
            # Si existe, la eliminamos ya que no está en el modelo actual
            cursor.execute("ALTER TABLE ventas_cliente DROP COLUMN IF EXISTS usuario_id;")
            print("Campo usuario_id eliminado de la tabla ventas_cliente")
        else:
            print("Campo usuario_id no encontrado en la tabla ventas_cliente")


def reverse_fix_usuario_id_column(apps, schema_editor):
    """
    Función reversa - no hacemos nada ya que no queremos recrear el campo problemático
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_alter_venta_metodo_pago'),
    ]

    operations = [
        migrations.RunPython(
            fix_usuario_id_column,
            reverse_fix_usuario_id_column,
        ),
    ] 