# Generated by Django manually to fix usuario_id column issue in ventas_venta

from django.db import migrations, models
from django.db import connection


def fix_venta_usuario_id_column(apps, schema_editor):
    """
    Función para manejar el campo usuario_id problemático en ventas_venta
    """
    with connection.cursor() as cursor:
        # Verificar si la columna usuario_id existe en ventas_venta
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name = 'ventas_venta' AND column_name = 'usuario_id';
        """)
        
        if cursor.fetchone():
            # Si existe, la eliminamos ya que no está en el modelo actual
            cursor.execute("ALTER TABLE ventas_venta DROP COLUMN IF EXISTS usuario_id;")
            print("Campo usuario_id eliminado de la tabla ventas_venta")
        else:
            print("Campo usuario_id no encontrado en la tabla ventas_venta")


def reverse_fix_venta_usuario_id_column(apps, schema_editor):
    """
    Función reversa - no hacemos nada ya que no queremos recrear el campo problemático
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_fix_usuario_id_column'),
    ]

    operations = [
        migrations.RunPython(
            fix_venta_usuario_id_column,
            reverse_fix_venta_usuario_id_column,
        ),
    ] 