# Generated by Django 5.2.4 on 2025-08-11 21:36

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0005_fix_venta_usuario_id_column'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='porcentaje_descuento',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Porcentaje de descuento aplicado a la venta (0-100)', max_digits=5, verbose_name='Porcentaje de descuento'),
        ),
    ]
