# Configuración de Dependabot para mantener las dependencias actualizadas
# https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # Mantener actualizadas las dependencias de npm
  - package-ecosystem: "npm"
    directory: "/Localix-dashboard"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "miguelnexs"
    assignees:
      - "miguelnexs"
    commit-message:
      prefix: "npm"
      prefix-development: "npm-dev"
      include: "scope"

  # Mantener actualizadas las dependencias de pip
  - package-ecosystem: "pip"
    directory: "/Localix-backend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "miguelnexs"
    assignees:
      - "miguelnexs"
    commit-message:
      prefix: "pip"
      include: "scope"

  # Mantener actualizadas las dependencias de GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "miguelnexs"
    assignees:
      - "miguelnexs"
    commit-message:
      prefix: "github-actions"
      include: "scope"

  # Mantener actualizadas las dependencias de Docker (si se usa en el futuro)
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "miguelnexs"
    assignees:
      - "miguelnexs"
    commit-message:
      prefix: "docker"
      include: "scope"
