# Configuración de etiquetas para el repositorio
# https://github.com/miguelnexs/localix/labels

labels:
  # 🐛 Bugs
  - name: "bug"
    color: "d73a4a"
    description: "Something isn't working"

  # 🚀 Features
  - name: "enhancement"
    color: "a2eeef"
    description: "New feature or request"

  # 📚 Documentation
  - name: "documentation"
    color: "0075ca"
    description: "Improvements or additions to documentation"

  # 🎨 UI/UX
  - name: "ui/ux"
    color: "fef2c0"
    description: "User interface and user experience improvements"

  # 🔧 Backend
  - name: "backend"
    color: "0e8a16"
    description: "Backend related changes (Django, API)"

  # 🎯 Frontend
  - name: "frontend"
    color: "1d76db"
    description: "Frontend related changes (React, Electron)"

  # 🧪 Testing
  - name: "testing"
    color: "c2e0c6"
    description: "Adding or improving tests"

  # 🔒 Security
  - name: "security"
    color: "ff0000"
    description: "Security related issues"

  # ⚡ Performance
  - name: "performance"
    color: "ffa500"
    description: "Performance improvements"

  # 🚨 Breaking Change
  - name: "breaking-change"
    color: "d93f0b"
    description: "Changes that break existing functionality"

  # 🔄 Refactoring
  - name: "refactoring"
    color: "6f42c1"
    description: "Code refactoring"

  # 🚀 Deployment
  - name: "deployment"
    color: "00ff00"
    description: "Deployment related changes"

  # 🐳 Docker
  - name: "docker"
    color: "2496ed"
    description: "Docker related changes"

  # 📦 Dependencies
  - name: "dependencies"
    color: "0366d6"
    description: "Dependency updates"

  # 🎯 Good First Issue
  - name: "good first issue"
    color: "7057ff"
    description: "Good for newcomers"

  # 🏷️ Help Wanted
  - name: "help wanted"
    color: "008672"
    description: "Extra attention is needed"

  # 🚫 Invalid
  - name: "invalid"
    color: "e4e669"
    description: "Something is wrong"

  # ❓ Question
  - name: "question"
    color: "d876e3"
    description: "Further information is requested"

  # 🚧 Wontfix
  - name: "wontfix"
    color: "ffffff"
    description: "This will not be worked on"

  # 🔥 Hotfix
  - name: "hotfix"
    color: "ff0000"
    description: "Critical bug fix that needs immediate attention"

  # 📊 Analytics
  - name: "analytics"
    color: "1abc9c"
    description: "Analytics and reporting features"

  # 🛒 Sales
  - name: "sales"
    color: "e67e22"
    description: "Sales and inventory management"

  # 👥 Customers
  - name: "customers"
    color: "9b59b6"
    description: "Customer management features"

  # 📈 Reports
  - name: "reports"
    color: "3498db"
    description: "Reporting and analytics features"

  # 🔍 Search
  - name: "search"
    color: "2ecc71"
    description: "Search functionality improvements"

  # 📱 Mobile
  - name: "mobile"
    color: "f39c12"
    description: "Mobile-specific features or fixes"

  # 🌐 API
  - name: "api"
    color: "34495e"
    description: "API related changes"

  # 💾 Database
  - name: "database"
    color: "8e44ad"
    description: "Database related changes"

  # 🔐 Authentication
  - name: "authentication"
    color: "e74c3c"
    description: "Authentication and authorization"

  # 📤 Export
  - name: "export"
    color: "27ae60"
    description: "Data export features (Excel, CSV, etc.)"

  # 📥 Import
  - name: "import"
    color: "2980b9"
    description: "Data import features"

  # 🎨 Theme
  - name: "theme"
    color: "f1c40f"
    description: "Theme and styling changes"

  # 🔔 Notifications
  - name: "notifications"
    color: "e67e22"
    description: "Notification system"

  # 📅 Calendar
  - name: "calendar"
    color: "3498db"
    description: "Calendar and scheduling features"

  # 💰 Billing
  - name: "billing"
    color: "2ecc71"
    description: "Billing and payment features"

  # 📊 Dashboard
  - name: "dashboard"
    color: "9b59b6"
    description: "Dashboard improvements"

  # 🔍 Audit
  - name: "audit"
    color: "e74c3c"
    description: "Audit trail and logging"

  # 🚀 Release
  - name: "release"
    color: "27ae60"
    description: "Release related tasks"
