# Generated by Django 5.2.4 on 2025-07-19 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Rojo, Azul, Verde, etc.', max_length=100, verbose_name='Nombre del color')),
                ('hex_code', models.CharField(help_text='Código de color en formato #RRGGBB', max_length=7, verbose_name='Código hexadecimal')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden de visualización')),
                ('activo', models.BooleanField(default=True, help_text='Indica si el color está disponible', verbose_name='Color activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colores', to='productos.producto', verbose_name='Producto asociado')),
            ],
            options={
                'verbose_name': 'Color de producto',
                'verbose_name_plural': 'Colores de productos',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='ImagenProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(help_text='Imagen del producto en este color', upload_to='productos/colores/', verbose_name='Imagen')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden de visualización')),
                ('es_principal', models.BooleanField(default=False, help_text='Indica si es la imagen principal del color', verbose_name='Imagen principal')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='productos.colorproducto', verbose_name='Color asociado')),
            ],
            options={
                'verbose_name': 'Imagen de producto',
                'verbose_name_plural': 'Imágenes de productos',
                'ordering': ['color', 'orden', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='colorproducto',
            index=models.Index(fields=['producto'], name='productos_c_product_21b594_idx'),
        ),
        migrations.AddIndex(
            model_name='colorproducto',
            index=models.Index(fields=['nombre'], name='productos_c_nombre_fed12d_idx'),
        ),
        migrations.AddIndex(
            model_name='colorproducto',
            index=models.Index(fields=['activo'], name='productos_c_activo_d4334e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='colorproducto',
            unique_together={('producto', 'nombre')},
        ),
        migrations.AddIndex(
            model_name='imagenproducto',
            index=models.Index(fields=['color'], name='productos_i_color_i_2acb03_idx'),
        ),
        migrations.AddIndex(
            model_name='imagenproducto',
            index=models.Index(fields=['orden'], name='productos_i_orden_7a4439_idx'),
        ),
        migrations.AddIndex(
            model_name='imagenproducto',
            index=models.Index(fields=['es_principal'], name='productos_i_es_prin_e029b4_idx'),
        ),
        migrations.AddConstraint(
            model_name='imagenproducto',
            constraint=models.CheckConstraint(condition=models.Q(('orden__gte', 0)), name='orden_imagen_positivo'),
        ),
    ]
