# Generated by Django 5.2.4 on 2025-07-19 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_colorproducto_imagenproducto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='colorproducto',
            name='stock',
            field=models.IntegerField(default=0, help_text='Cantidad disponible para este color específico', verbose_name='Stock del color'),
        ),
        migrations.AddIndex(
            model_name='colorproducto',
            index=models.Index(fields=['stock'], name='productos_c_stock_dd104c_idx'),
        ),
    ]
