# Generated by Django 5.2.4 on 2025-08-19 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_alter_producto_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='colorproducto',
            name='stock_reservado',
            field=models.IntegerField(default=0, help_text='Unidades reservadas pendientes de completar', verbose_name='Stock reservado (color)'),
        ),
        migrations.AddField(
            model_name='varianteproducto',
            name='stock_reservado',
            field=models.IntegerField(default=0, help_text='Unidades reservadas pendientes de completar', verbose_name='Stock reservado (variante)'),
        ),
    ]
