# Generated by Django 5.2.4 on 2025-07-20 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_colorproducto_stock_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='categorias_secundarias',
        ),
    ]
