# Generated by Django 5.2.4 on 2025-08-19 04:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserUsagePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.CharField(choices=[('trial', 'Prueba Gratuita'), ('basic', 'Plan Básico'), ('premium', 'Plan Premium'), ('custom', 'Plan Personalizado')], default='trial', max_length=20)),
                ('days_allowed', models.IntegerField(default=15, help_text='Número de días permitidos de uso')),
                ('start_date', models.DateTimeField(auto_now_add=True, help_text='Fecha de inicio del plan')),
                ('end_date', models.DateTimeField(help_text='Fecha de expiración del plan')),
                ('is_active', models.BooleanField(default=True, help_text='Si el plan está activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usage_plan', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plan de Uso de Usuario',
                'verbose_name_plural': 'Planes de Uso de Usuarios',
            },
        ),
    ]
