# Generated by Django 5.2.4 on 2025-08-19 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_userusageplan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userusageplan',
            name='end_date',
            field=models.DateTimeField(blank=True, help_text='Fecha de expiración del plan', null=True),
        ),
    ]
