# Generated by Django 5.2.3 on 2025-06-27 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre único de la categoría', max_length=100, unique=True, verbose_name='Nombre')),
                ('slug', models.SlugField(help_text='Identificador único para URLs', max_length=110, unique=True, verbose_name='Slug')),
                ('descripcion', models.TextField(blank=True, help_text='Información adicional sobre la categoría', null=True, verbose_name='Descripción')),
                ('activa', models.BooleanField(default=True, help_text='Indica si la categoría está disponible', verbose_name='Activa')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden de visualización')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='categorias/', verbose_name='Imagen representativa')),
            ],
            options={
                'verbose_name': 'Categoría de producto',
                'verbose_name_plural': 'Categorías de productos',
                'ordering': ['orden', 'nombre'],
                'abstract': False,
                'indexes': [models.Index(fields=['nombre'], name='categorias__nombre_cbe9e9_idx'), models.Index(fields=['slug'], name='categorias__slug_aa9e7a_idx')],
            },
        ),
    ]
