# Generated by Django 5.2.4 on 2025-08-15 18:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre único de la categoría', max_length=100, unique=True, verbose_name='Nombre')),
                ('slug', models.SlugField(help_text='Identificador único para URLs', max_length=110, unique=True, verbose_name='Slug')),
                ('descripcion', models.TextField(blank=True, help_text='Información adicional sobre la categoría', null=True, verbose_name='Descripción')),
                ('activa', models.BooleanField(default=True, help_text='Indica si la categoría está disponible', verbose_name='Activa')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden de visualización')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='categorias/', verbose_name='Imagen representativa')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro', verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última actualización', verbose_name='Fecha de actualización')),
                ('usuario', models.ForeignKey(help_text='Usuario que posee esta categoría', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario propietario')),
            ],
            options={
                'verbose_name': 'Categoría de producto',
                'verbose_name_plural': 'Categorías de productos',
                'indexes': [models.Index(fields=['usuario', 'nombre'], name='categorias__usuario_c39e7d_idx'), models.Index(fields=['usuario', 'slug'], name='categorias__usuario_0f4c9b_idx')],
            },
        ),
    ]
