# Generated by Django 5.2.4 on 2025-07-18 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriaproducto',
            options={'verbose_name': 'Categoría de producto', 'verbose_name_plural': 'Categorías de productos'},
        ),
        migrations.RemoveIndex(
            model_name='categoriaproducto',
            name='categorias__nombre_cbe9e9_idx',
        ),
        migrations.RemoveIndex(
            model_name='categoriaproducto',
            name='categorias__slug_aa9e7a_idx',
        ),
    ]
