# Generated by Django 5.2.4 on 2025-08-15 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriaproducto',
            name='nombre',
            field=models.CharField(help_text='Nombre de la categoría', max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='categoriaproducto',
            name='slug',
            field=models.SlugField(help_text='Identificador único para URLs', max_length=110, verbose_name='Slug'),
        ),
    ]
