# Generated by Django 5.2.4 on 2025-08-11 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0002_alter_categoriaproducto_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriaproducto',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última actualización', verbose_name='Fecha de actualización'),
        ),
        migrations.AddField(
            model_name='categoriaproducto',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=1, help_text='Fecha y hora de creación del registro', verbose_name='Fecha de creación'),
            preserve_default=False,
        ),
    ]
