# Generated by Django 5.2.4 on 2025-07-21 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
        ('productos', '0004_remove_producto_categorias_secundarias'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempedido',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='productos.colorproducto', verbose_name='Color específico'),
        ),
    ]
