# Generated by Django 5.2.4 on 2025-08-19 20:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_pedido_monto_abono_pedido_monto_pendiente_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Abono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_abono', models.DateTimeField(default=django.utils.timezone.now)),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta de Crédito/Débito'), ('transferencia', 'Transferencia Bancaria'), ('cheque', 'Cheque'), ('paypal', 'PayPal'), ('otro', 'Otro')], max_length=20)),
                ('referencia_pago', models.CharField(blank=True, max_length=100)),
                ('estado_abono', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado'), ('rechazado', 'Rechazado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=15)),
                ('notas', models.TextField(blank=True)),
                ('fecha_confirmacion', models.DateTimeField(blank=True, null=True)),
                ('comprobante', models.CharField(blank=True, max_length=200)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonos', to='pedidos.pedido')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Abono',
                'verbose_name_plural': 'Abonos',
                'ordering': ['-fecha_abono'],
                'indexes': [models.Index(fields=['pedido', 'estado_abono'], name='pedidos_abo_pedido__b10928_idx'), models.Index(fields=['fecha_abono'], name='pedidos_abo_fecha_a_d2160d_idx'), models.Index(fields=['metodo_pago'], name='pedidos_abo_metodo__bd6c57_idx')],
            },
        ),
        migrations.CreateModel(
            name='EstadoPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado'), ('en_preparacion', 'En Preparación'), ('enviado', 'Enviado'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado'), ('separado', 'Separado')], max_length=20)),
                ('fecha_cambio', models.DateTimeField(default=django.utils.timezone.now)),
                ('notas', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estados', to='pedidos.pedido')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Estado de Pedido',
                'verbose_name_plural': 'Estados de Pedidos',
                'ordering': ['-fecha_cambio'],
                'indexes': [models.Index(fields=['pedido', 'activo'], name='pedidos_est_pedido__e23650_idx'), models.Index(fields=['estado', 'fecha_cambio'], name='pedidos_est_estado_8f4c2d_idx')],
            },
        ),
    ]
