name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test-backend:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        cd Localix-backend
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run tests
      run: |
        cd Localix-backend
        python manage.py test

  test-frontend:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: Localix-dashboard/package-lock.json
    
    - name: Install dependencies
      run: |
        cd Localix-dashboard
        npm ci
    
    - name: Run linting
      run: |
        cd Localix-dashboard
        npm run lint
    
    - name: Run tests
      run: |
        cd Localix-dashboard
        npm test
    
    - name: Build
      run: |
        cd Localix-dashboard
        npm run build

  security:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Run security audit
      run: |
        cd Localix-dashboard
        npm audit --audit-level moderate
